pom: do not build installer by default
This effectively reverts 5a16050 'Revert "Do not build installer by
default"' 2012-04-07. There seems to be a bug in jenkins, which causes
the build to fail in izpack submodule. So let's remove izpack from the
default build, again.

Relevant part seems to be:

[INFO] ------------------------------------------------------------------------
[INFO] Building svarog-installer
[INFO]    task-segment: [package]
...
[INFO] [surefire:test {execution: default-test}]
[INFO] Tests are skipped.
[INFO] [jar:jar {execution: default-jar}]
[INFO] Building jar: /var/lib/jenkins/workspace/svarog-installer/izpack/target/svarog-installer-0.5.0-SNAPSHOT.jar
[INFO] [izpack:izpack {execution: default}]
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /var/lib/jenkins/workspace/svarog-installer/izpack/src/izpack
Warning: CustomAction jar file not found: /var/lib/jenkins/workspace/svarog-installer/izpack/bin/customActions/Uninstaller.jar
[JENKINS] Archiving /var/lib/jenkins/workspace/svarog-installer/izpack/pom.xml to /var/lib/jenkins/jobs/svarog-installer/modules/org.signalml$svarog-installer/builds/2012-04-25_10-57-16/archive/org.signalml/svarog-installer/0.5.0-SNAPSHOT/svarog-installer-0.5.0-SNAPSHOT.pom
[JENKINS] Archiving /var/lib/jenkins/workspace/svarog-installer/izpack/target/svarog-installer-0.5.0-SNAPSHOT.jar to /var/lib/jenkins/jobs/svarog-installer/modules/org.signalml$svarog-installer/builds/2012-04-25_10-57-16/archive/org.signalml/svarog-installer/0.5.0-SNAPSHOT/svarog-installer-0.5.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] IzPack compilation ERROR

Embedded error: /var/lib/jenkins/workspace/svarog-installer/izpack/install.xml:73: /var/lib/jenkins/workspace/svarog-installer/izpack/svarog.jar
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: IzPack compilation ERROR
...
Caused by: com.izforge.izpack.compiler.CompilerException: /var/lib/jenkins/workspace/svarog-installer/izpack/install.xml:73: /var/lib/jenkins/workspace/svarog-installer/izpack/svarog.jar
       at com.izforge.izpack.compiler.CompilerConfig.parseError(Unknown Source)
       at com.izforge.izpack.compiler.CompilerConfig.addPacksSingle(Unknown Source)
       at com.izforge.izpack.compiler.CompilerConfig.addPacks(Unknown Source)
       at com.izforge.izpack.compiler.CompilerConfig.executeCompiler(Unknown Source)
       at org.izpack.mojo.IzPackMojo.buildInstaller(IzPackMojo.java:247)
       ... 32 more
Caused by: java.io.FileNotFoundException: /var/lib/jenkins/workspace/svarog-installer/izpack/svarog.jar
       at com.izforge.izpack.compiler.PackInfo.addFile(Unknown Source)
       at com.izforge.izpack.compiler.CompilerConfig.addRecursively(Unknown Source)
       ... 36 more

In a healthy build (same machine, but not through jenkins):

[INFO] [surefire:test {execution: default-test}]
[INFO] Tests are skipped.
[INFO] [dependency:copy {execution: copy}]
[INFO] Configured Artifact: org.signalml:svarog:onejar:0.5.0-SNAPSHOT:jar
[INFO] Configured Artifact: org.signalml.plugin:FFT:0.1:jar
[INFO] Configured Artifact: org.signalml.plugin:FFTSignalTool:0.1:jar
[INFO] Configured Artifact: org.signalml.plugin:PluginToolCommon:0.1:jar
[INFO] Configured Artifact: org.signalml.plugin:Artifact:0.1:jar
[INFO] Copying svarog-0.5.0-SNAPSHOT-onejar.jar to /var/data/jenkins/workspace/svarog-installer/izpack/svarog.jar
[INFO] Copying FFT-0.1.jar to /var/data/jenkins/workspace/svarog-installer/izpack/plugins/FFT.jar
[INFO] Copying FFTSignalTool-0.1.jar to /var/data/jenkins/workspace/svarog-installer/izpack/plugins/FFTSignalTool.jar
[INFO] Copying PluginToolCommon-0.1.jar to /var/data/jenkins/workspace/svarog-installer/izpack/plugins/PluginToolCommon.jar
[INFO] Copying Artifact-0.1.jar to /var/data/jenkins/workspace/svarog-installer/izpack/plugins/Artifact.jar
[INFO] [jar:jar {execution: default}]
[INFO] [jar:jar {execution: default-jar}]

So the copy phase is skipped.

The izpack module is configured in a "profile", so the installer can
still be built together with the rest of Svarog:

  mvn -P installer ... package

but not by default.