Catch exception thrown when reading application config
After removing Artefact and Stager this problem cropped up.

2011-10-07 15:16:51,584 DEBUG [org.signalml.app.SvarogApplication] - Application starting
2011-10-07 15:16:53,004 DEBUG [org.signalml.app.config.AbstractXMLConfiguration] - Reading [ApplicationConfiguration] from file [/home/zbyszek/signalml/application-config.xml]
[23/Svarog app] [error]: uncaught exception [com.thoughtworks.xstream.converters.ConversionException: artifactConfig : artifactConfig
---- Debugging information ----
message             : artifactConfig : artifactConfig
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message       : artifactConfig : artifactConfig
class               : org.signalml.app.config.ApplicationConfiguration
required-type       : org.signalml.app.config.ApplicationConfiguration
-------------------------------] in thread [23/Svarog app]
com.thoughtworks.xstream.converters.ConversionException: artifactConfig : artifactConfig
---- Debugging information ----
message             : artifactConfig : artifactConfig
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message       : artifactConfig : artifactConfig
class               : org.signalml.app.config.ApplicationConfiguration
required-type       : org.signalml.app.config.ApplicationConfiguration
-------------------------------
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:63)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:46)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:117)
        at com.thoughtworks.xstream.core.TreeMarshallingStrategy.unmarshal(TreeMarshallingStrategy.java:14)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:846)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:833)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:816)
        at org.signalml.app.util.XMLUtils.objectFromFile(XMLUtils.java:201)
        at org.signalml.app.config.AbstractXMLConfiguration.readFromXML(AbstractXMLConfiguration.java:43)
        at org.signalml.app.config.AbstractXMLConfiguration.readFromPersistence(AbstractXMLConfiguration.java:70)
        at org.signalml.app.config.AbstractXMLConfiguration.maybeReadFromPersistence(AbstractXMLConfiguration.java:75)
        at org.signalml.app.SvarogApplication.createApplication(SvarogApplication.java:642)
        at org.signalml.app.SvarogApplication.mainPart2(SvarogApplication.java:369)
        at org.signalml.app.SvarogApplication.run(SvarogApplication.java:266)
        at java.lang.Thread.run(Thread.java:636)
Caused by: com.thoughtworks.xstream.mapper.CannotResolveClassException: artifactConfig : artifactConfig
        at com.thoughtworks.xstream.mapper.DefaultMapper.realClass(DefaultMapper.java:49)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:26)
        at com.thoughtworks.xstream.mapper.ClassAliasingMapper.realClass(ClassAliasingMapper.java:76)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:26)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:26)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:26)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:26)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:26)
        at com.thoughtworks.xstream.mapper.DynamicProxyMapper.realClass(DynamicProxyMapper.java:60)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:26)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:26)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:26)
        at com.thoughtworks.xstream.mapper.ArrayMapper.realClass(ArrayMapper.java:76)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:26)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:26)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:26)
        at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper.java:34)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.determineType(AbstractReflectionConverter.java:296)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:178)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:125)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:56)
        ... 14 more