Path to Artifact config.xml was broken
java.io.FileNotFoundException: class path resource [resources/org/signalml/plugin/newartifact/resource/config.xml] cannot be opened because it does not exist